# -*- coding: utf-8 -*-
"""1: Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DogSYx2MYsb7mqzCx326k44GsFC64dC
"""

# Mini Project 1: Basic Calculator

# Get user input
while True:
  num1 = float(input("Enter first number:"))
  operator = input("Enter operator (+,-,*,/):")
  num2 = float(input("Enter second number:"))

  #Perform calculation based on operator
  if operator == "+":
    result = num1 + num2
  elif operator == "-":
    result = num1 - num2
  elif operator == "*":
    result = num1 * num2
  elif operator == "/":
    if num2 != 0:
      result = num1 / num2
    else:
        result = "Error: Cannot divide by zero."
  else:
    result = "Invalid operator."

  # Show result
  print ("Result:", result)

  #Ask if they want to continue
  again = input("Do you want to calculate again? (yes/no):")
  if again.lower() != "yes":
          print("Goodbye!")
          break

#Grade Calculator

#Loop for recalculating
while True:
#Loop for first input, current grade
  while True:
  #get user input
    grade = float(input("Enter your current grade as a percentage (example 89.3):"))
  #check that input is correct
    try:
      if grade < 1:
        print ("Did you mean to enter a percentage? (Example 89.3, not 0.893)")
        continue
      else:
        print(f"You entered: {grade: .1f}%")
        #moves to next loop
        break
    except ValueError:
      print("Invalid input! Please enter a number like 89.3, not a letter grade.")
 #loop for second input, overall grade
  while True:
    overall = float(input("Enter the final course grade you want (example 90 for 90%) "))
    try:
      if overall < 1:
        print ("Did you mean to enter a percentage? (Example 89.3, not 0.893)")
        continue
      else:
        print(f"You entered: {overall: .1f}%")
        #moves to give needed final grade
        break
    except ValueError:
      print("Invalid input! Please enter a number like 89.3, not a letter grade.")

  #perform calculations for needed final grade
  fgrade = (overall - grade*0.85)/0.15
  #rounds needed final grade
  fgrade = round(fgrade,2)
  #accounts for if % is less than 0
  if fgrade < 0:
    fgrade = 0
  #accounts for if $ is larger than 100 and returns heartbreak
  if fgrade < 100:
    print ("To earn a", overall, "% in the course, you need to earn at least a", fgrade, "% on the final exam.")
  #returns final needed grade
  else:
    print ("Based on your current grade", grade, "%, It is not possible for you to earn a", overall, "% in the course. Please recalculate for a lower possible course grade.")

  #Ask if they want to continue
  again = input("Do you want to calculate again? (yes/no):")
  if again.lower() != "yes":
          print("Good Luck on your Final!")
          break