# -*- coding: utf-8 -*-
"""2. Coin flip

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zds00SeQDBc8OnWC1zYqR2mJtCpVUJgj
"""

# Mini Project 2: Coin Flip Simulator

import random

#Coin Flip Simulator

while True:
  #Flip the coin
  flip = random.choice(["Heads","Tails"])
  print("You flipped:", flip)

  #Ask if the user wants to flip again
  again = input("Do you want to flip again? (yes/no):")
  if again.lower() != "yes":
    print("Thanks for playing!")
    break

# My version: What's for dinner?

import random

#What's for dinner?

food = ["Italian","Chinese","American","Mexican"]
user_quit = False

while food: #as long as there are options left

  pick = random.choice(food)
  print("Tonight you're eating:",pick)
  #remove cuisine so it won't be suggested again
  food.remove(pick) #remove item so its not suggested again
  #ask if user wants to try again
  again = input("Does that sound tasty? (yes/no)")
  if again.lower() !="no":
    user_quit = True
    break
if user_quit:
   print("Enjoy your",pick,"meal!")
else:
  print("No more options are left for you to choose. Are you sure you're hungry?")